[package]
name = "dotlottie-ffi"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "dlplayer"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.24.3", features = ["cli"] }
# Core runtime
dotlottie_player = { path = "../dotlottie-rs" }

[build-dependencies]
uniffi = { version = "0.24.3", features = ["build"] }
