[package]
name = "rust-bindings"
version = "0.1.0"
edition = "2021"
links = "thorvg"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.25"

[build-dependencies]
bindgen = "0.65.1"